spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: ${PORT:8083}

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:guest}
  password: ${RABBITMQ_PASSWORD:guest}

groq:
  api:
    url: "https://api.groq.com/openai/v1/chat/completions"
    key: "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"
