spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}
  instance:
    hostname: localhost
    prefer-ip-address: true

server:
  port: ${PORT:8083}

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}

groq:
  api:
    url: "https://api.groq.com/openai/v1/chat/completions"
    key: ${GROQ_API_KEY}
