spring:
  mongodb:
    uri: {Mongodb_uri}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: ${PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/


rabbitmq:
  exchange:
    name: mealplan.exchange
  queue:
    name: mealplan.queue
  routing:
    key: mealplan.routing
  workout:
    exchange:
      name: workoutplan.exchange
    queue:
      name: workoutplan.queue
    routing:
      key: workoutplan.routing

groq:
  api:
    url: "https://api.groq.com/openai/v1/chat/completions"
    key: {Grok_key}
