spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: fitness_mealplan
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
server:
  port: ${PORT:8084}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
rabbitmq:
  exchange:
    name: mealplan.exchange
  queue:
    name: mealplan.queue
  routing:
    key: mealplan.routing
  workout:
    exchange:
      name: workoutplan.exchange
    queue:
      name: workoutplan.queue
    routing:
      key: workoutplan.routing
groq:
  api:
    url: "https://api.groq.com/openai/v1/chat/completions"
    key: ${GROQ_API_KEY}
