spring:
  data:
    mongodb:
      uri: "mongodb+srv://amandwivedikusmara_db_user:IiNklBD3bO8udN1g@amandwivedi34.zr7gaav.mongodb.net/?appName=AmanDwivedi34"
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: ${PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: mealplan.exchange
  queue:
    name: mealplan.queue
  routing:
    key: mealplan.routing
  workout:
    exchange:
      name: workoutplan.exchange
    queue:
      name: workoutplan.queue
    routing:
      key: workoutplan.routing

groq:
  api:
    url: "https://api.groq.com/openai/v1/chat/completions"
    key: "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"
