spring:
  datasource:
    url: {MySql_uri}

    username: {MySql_username}
    password: {Mysql_Password}
    #driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

