package com.fitness.aihelper.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.List;

/**
 * A workout plan generated by the AI service.
 *
 * Lifecycle:
 *   1. Controller receives a {@link com.fitness.aihelper.dto.WorkoutPlanRequest},
 *      builds a WorkoutPlan with status PENDING, and persists it.
 *   2. The plan JSON is published to RabbitMQ.
 *   3. The listener calls the AI service to populate {@link #workoutDays}.
 *   4. On success the status flips to COMPLETED; on failure, FAILED.
 */
@Document(collection = "workout_plans")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WorkoutPlan {
    public static final String STATUS_PENDING = "PENDING";
    public static final String STATUS_COMPLETED = "COMPLETED";
    public static final String STATUS_FAILED = "FAILED";

    @Id
    private String id;
    private String userId;

    // --- Request snapshot ---
    private Integer age;
    private Double weight;    // kg
    private Double height;    // cm
    /** MUSCLE_GAIN, WEIGHT_LOSS, ENDURANCE, MAINTENANCE, GENERAL_FITNESS */
    private String goal;
    /** How many workout days to generate */
    private Integer days;
    /** Desired session duration in minutes */
    private Integer durationInMinutes;
    /** MALE, FEMALE, OTHER */
    private String gender;
    /** BEGINNER, INTERMEDIATE, ADVANCED */
    private String experienceLevel;
    /** COMMERCIAL_GYM, HOME_GYM, BODYWEIGHT, OUTDOOR */
    private String location;
    /** Selected equipment, e.g. ["Barbell", "Dumbbells", "Cable Machine"] */
    private List<String> equipment;
    /**
     * Free-form user suggestions/preferences (raw text). Snapshot here so the
     * prompt the AI worker builds is self-contained.
     */
    private String suggestion;

    // --- Generated content ---
    /** One entry per requested day. Empty until the AI worker runs. */
    private List<WorkoutDay> workoutDays;
    private String status;

    @CreatedDate
    private LocalDateTime createdAt;
    @LastModifiedDate
    private LocalDateTime updatedAt;
}
